---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: go-app2
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./video7/environments/dev/go-app2
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: goapp2-ns
  timeout: 3m0s
  wait: true
