---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: python-app
  namespace: flux-system
spec:
  dependsOn:
    - name: python-app-pre-deploy
  interval: 30m0s
  path: ./flux-and-data-migrations/kubernetes/deploy/
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: python-app-ns
  timeout: 3m0s
  wait: true
