apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: python-app-ns
resources:
  - namespace.yaml
  - pvc.yaml
  - image-repository.yaml
  - db-migration.yaml
images:
  - name: ghcr.io/cultura-do-caractere/python-app # {"$imagepolicy": "python-app-ns:python-app:name"}
    newTag: 0.0.59 # {"$imagepolicy": "python-app-ns:python-app:tag"}
