---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: go-app
  namespace: cdc-dev
spec:
  image: ghcr.io/cultura-do-caractere/golang-app
  interval: 10h
  provider: generic
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: go-app
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: go-app
    namespace: cdc-dev
  policy:
    semver:
      range: ^0.0.0
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: go-app
  namespace: cdc-dev
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
    push:
      branch: main
  update:
    path: ./video7/cluster/environments/dev/go-app/