apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cdc-dev
resources:
  - ../../../apps/go-app
  - image-repository.yaml
images:
  - name: ghcr.io/cultura-do-caractere/golang-app # {"$imagepolicy": "cdc-dev:go-app:name"}
    newTag: 0.0.28 # {"$imagepolicy": "cdc-dev:go-app:tag"}
