"""adding column first_name

Revision ID: fff027427cbf
Revises: d18240eb6e0e
Create Date: 2024-08-24 17:54:17.481312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fff027427cbf'
down_revision: Union[str, None] = 'd18240eb6e0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
