apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cdc-prod
resources:      
  - ../../apps
patches:
  - target:
      kind: Ingress
      name: golang-app
    patch: |-
      - op: replace #action 
        path: /spec/rules/0/host #resouirce we want to change
        value: golang-app.prod
