apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cdc-stg
resources:      
  - ../../apps
patches:
  - target:
      kind: Ingress
      name: golang-app
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: golang-app-stg
