services:
  web:
    build: 
      context: .
      dockerfile: src/Dockerfile
    ports:
      - "8000:1323"
    develop:
      watch:
        - action: rebuild
          path: ./src
  postgres:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    volumes:
    - ./postgres/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres