name: CI and CD Go App

on:
    push:
      paths:
      - video7/go-app2/**
      - video7/environments/dev/go-app2/**

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: cultura-do-caractere/golang-app2

jobs:
    build-and-push-image:
      runs-on: ubuntu-latest

      permissions:
          contents: read
          packages: write
          attestations: write
          id-token: write

      steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: video7/go-app2/Dockerfile
          push: true
          tags: "ghcr.io/cultura-do-caractere/golang-app2:0.0.${{github.run_number}}"